version: "3.5"

volumes:
  pg_project:

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=stage
    volumes:
      - pg_project:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432
  ig:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - 5005:5005
      - 9229:9229
    volumes:
      - ./:/app
    depends_on:
      - pg_db
  