{{- define "worker.tpl" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" (include "worker" .) .env.name }}
  labels:
    {{- include "chart.workerLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "chart.workerSelectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "chart.workerSelectorLabels" . | nindent 8 }}
        date: "{{ now | unixEpoch }}"
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}-{{ include "chart.name" . }}
      containers:
        - name: {{ printf "%s-%s-worker" (include "worker" .) .env.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
             {{- range $i, $value := .command }}
             - "{{ $value }}"
             {{- end }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          resources:
            requests:
               cpu: {{ .env.cpu_request }}
               memory: {{ .env.memory_request }}
            limits:
               memory: {{ .env.memory_limit }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- end }}
