apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.name" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
        date: "{{ now | unixEpoch }}"
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}-{{ include "chart.name" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "chart.name" .  }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- if .Values.entrypoint.enabled }}
          command: {{ .Values.command | toJson }}
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
            - name: debug
              containerPort: 9229
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.healthchecks }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
              httpHeaders: 
              - name: Probe-Type
                value: liveness
            initialDelaySeconds: 10
            failureThreshold: 3
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
              httpHeaders: 
              - name: Probe-Type
                value: readiness
            initialDelaySeconds: 10
            failureThreshold: 3
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
              httpHeaders: 
              - name: Probe-Type
                value: startup
            failureThreshold: 30
            periodSeconds: 10
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
