{{ if or .Values.migrations (not (hasKey .Values "migrations")) }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "chart.name" . }}-migrations
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
   "helm.sh/hook": pre-install,pre-upgrade
   "helm.sh/hook-weight": "10"
spec:
  activeDeadlineSeconds: 120
  backoffLimit: 1
  template:
    metadata:
      name: {{ include "chart.name" . }}-migrations
    spec:
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}-{{ include "chart.name" . }}
      containers:
      - name: {{ include "chart.name" . }}-migrations
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        command: ["npm", "run", "prisma:push"]
        env:
          {{- range $key, $value := .Values.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
      restartPolicy: Never
{{ end }}
