{{- define "vpa.tpl" }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ printf "%s-%s" (include "worker" .) .env.name }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{ printf "%s-%s" (include "worker" .) .env.name }}
  resourcePolicy: 
    containerPolicies:
      - containerName: "*"
        minAllowed:
          cpu: {{ .env.vpa_minAllowed_cpu }}
          memory: {{ .env.vpa_minAllowed_memory }}
        maxAllowed:
          cpu: {{ .env.vpa_maxAllowed_cpu }}
          memory: {{ .env.vpa_maxAllowed_memory }}
        controlledResources: ["cpu", "memory"]
        controlledValues: RequestsAndLimits
{{ end }}
